<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countrys = [
            ['country' => 'Afghanistan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AF'],
            ['country' => 'Åland Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AX'],
            ['country' => 'Albania', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AL'],
            ['country' => 'Algeria', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'DZ'],
            ['country' => 'American Samoa', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AS'],
            ['country' => 'Andorra', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AD'],
            ['country' => 'Angola', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AO'],
            ['country' => 'Anguilla', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AI'],
            ['country' => 'Antarctica', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AQ'],
            ['country' => 'Antigua and Barbuda', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AG'],
            ['country' => 'Argentina', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AR'],
            ['country' => 'Armenia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AM'],
            ['country' => 'Aruba', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AW'],
            ['country' => 'Australia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AU'],
            ['country' => 'Austria', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AT'],
            ['country' => 'Azerbaijan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AZ'],
            ['country' => 'Bahamas', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BS'],
            ['country' => 'Bahrain', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BH'],
            ['country' => 'Bangladesh', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BD'],
            ['country' => 'Barbados', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BB'],
            ['country' => 'Belarus', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BY'],
            ['country' => 'Belgium', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BE'],
            ['country' => 'Belize', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BZ'],
            ['country' => 'Benin', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BJ'],
            ['country' => 'Bermuda', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BM'],
            ['country' => 'Bhutan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BT'],
            ['country' => 'Bolivia, Plurinational State of', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BO'],
            ['country' => 'Bonaire, Sint Eustatius and Saba', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BQ'],
            ['country' => 'Bosnia and Herzegovina', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BA'],
            ['country' => 'Botswana', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BW'],
            ['country' => 'Bouvet Island', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BV'],
            ['country' => 'Brazil', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BR'],
            ['country' => 'British Indian Ocean Territory', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'IO'],
            ['country' => 'Brunei Darussalam', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BN'],
            ['country' => 'Bulgaria', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BG'],
            ['country' => 'Burkina Faso', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BF'],
            ['country' => 'Burundi', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BI'],
            ['country' => 'Cambodia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KH'],
            ['country' => 'Cameroon', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CM'],
            ['country' => 'Canada', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CA'],
            ['country' => 'Cape Verde', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CV'],
            ['country' => 'Cayman Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KY'],
            ['country' => 'Central African Republic', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CF'],
            ['country' => 'Chad', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TD'],
            ['country' => 'Chile', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CL'],
            ['country' => 'China', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CN'],
            ['country' => 'Christmas Island', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CX'],
            ['country' => 'Cocos (Keeling) Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CC'],
            ['country' => 'Colombia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CO'],
            ['country' => 'Comoros', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KM'],
            ['country' => 'Congo', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CG'],
            ['country' => 'Congo, the Democratic Republic of the', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CD'],
            ['country' => 'Cook Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CK'],
            ['country' => 'Costa Rica', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CR'],
            ['country' => 'Côte d\'Ivoire', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CI'],
            ['country' => 'Croatia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'HR'],
            ['country' => 'Cuba', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CU'],
            ['country' => 'Curaçao', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CW'],
            ['country' => 'Cyprus', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CY'],
            ['country' => 'Czech Republic', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CZ'],
            ['country' => 'Denmark', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'DK'],
            ['country' => 'Djibouti', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'DJ'],
            ['country' => 'Dominica', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'DM'],
            ['country' => 'Dominican Republic', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'DO'],
            ['country' => 'Ecuador', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'EC'],
            ['country' => 'Egypt', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'EG'],
            ['country' => 'El Salvador', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SV'],
            ['country' => 'Equatorial Guinea', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GQ'],
            ['country' => 'Eritrea', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'ER'],
            ['country' => 'Estonia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'EE'],
            ['country' => 'Ethiopia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'ET'],
            ['country' => 'Falkland Islands (Malvinas)', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'FK'],
            ['country' => 'Faroe Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'FO'],
            ['country' => 'Fiji', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'FJ'],
            ['country' => 'Finland', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'FI'],
            ['country' => 'France', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'FR'],
            ['country' => 'French Guiana', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GF'],
            ['country' => 'French Polynesia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PF'],
            ['country' => 'French Southern Territories', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TF'],
            ['country' => 'Gabon', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GA'],
            ['country' => 'Gambia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GM'],
            ['country' => 'Georgia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GE'],
            ['country' => 'Germany', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'DE'],
            ['country' => 'Ghana', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GH'],
            ['country' => 'Gibraltar', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GI'],
            ['country' => 'Greece', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GR'],
            ['country' => 'Greenland', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GL'],
            ['country' => 'Grenada', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GD'],
            ['country' => 'Guadeloupe', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GP'],
            ['country' => 'Guam', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GU'],
            ['country' => 'Guatemala', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GT'],
            ['country' => 'Guernsey', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GG'],
            ['country' => 'Guinea', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GN'],
            ['country' => 'Guinea-Bissau', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GW'],
            ['country' => 'Guyana', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GY'],
            ['country' => 'Haiti', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'HT'],
            ['country' => 'Heard Island and McDonald Mcdonald Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'HM'],
            ['country' => 'Holy See (Vatican City State)', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'VA'],
            ['country' => 'Honduras', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'HN'],
            ['country' => 'Hong Kong', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'HK'],
            ['country' => 'Hungary', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'HU'],
            ['country' => 'Iceland', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'IS'],
            ['country' => 'India', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'IN'],
            ['country' => 'Indonesia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'ID'],
            ['country' => 'Iran, Islamic Republic of', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'IR'],
            ['country' => 'Iraq', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'IQ'],
            ['country' => 'Ireland', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'IE'],
            ['country' => 'Isle of Man', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'IM'],
            ['country' => 'Israel', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'IL'],
            ['country' => 'Italy', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'IT'],
            ['country' => 'Jamaica', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'JM'],
            ['country' => 'Japan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'JP'],
            ['country' => 'Jersey', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'JE'],
            ['country' => 'Jordan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'JO'],
            ['country' => 'Kazakhstan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KZ'],
            ['country' => 'Kenya', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KE'],
            ['country' => 'Kiribati', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KI'],
            ['country' => 'Korea, Democratic People\'s Republic of', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KP'],
            ['country' => 'Korea, Republic of', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KR'],
            ['country' => 'Kuwait', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KW'],
            ['country' => 'Kyrgyzstan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KG'],
            ['country' => 'Lao People\'s Democratic Republic', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LA'],
            ['country' => 'Latvia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LV'],
            ['country' => 'Lebanon', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LB'],
            ['country' => 'Lesotho', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LS'],
            ['country' => 'Liberia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LR'],
            ['country' => 'Libya', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LY'],
            ['country' => 'Liechtenstein', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LI'],
            ['country' => 'Lithuania', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LT'],
            ['country' => 'Luxembourg', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LU'],
            ['country' => 'Macao', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MO'],
            ['country' => 'Macedonia, the Former Yugoslav Republic of', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MK'],
            ['country' => 'Madagascar', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MG'],
            ['country' => 'Malawi', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MW'],
            ['country' => 'Malaysia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MY'],
            ['country' => 'Maldives', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MV'],
            ['country' => 'Mali', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'ML'],
            ['country' => 'Malta', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MT'],
            ['country' => 'Marshall Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MH'],
            ['country' => 'Martinique', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MQ'],
            ['country' => 'Mauritania', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MR'],
            ['country' => 'Mauritius', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MU'],
            ['country' => 'Mayotte', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'YT'],
            ['country' => 'Mexico', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MX'],
            ['country' => 'Micronesia, Federated States of', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'FM'],
            ['country' => 'Moldova, Republic of', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MD'],
            ['country' => 'Monaco', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MC'],
            ['country' => 'Mongolia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MN'],
            ['country' => 'Montenegro', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'ME'],
            ['country' => 'Montserrat', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MS'],
            ['country' => 'Morocco', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MA'],
            ['country' => 'Mozambique', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MZ'],
            ['country' => 'Myanmar', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MM'],
            ['country' => 'Namibia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NA'],
            ['country' => 'Nauru', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NR'],
            ['country' => 'Nepal', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NP'],
            ['country' => 'Netherlands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NL'],
            ['country' => 'New Caledonia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NC'],
            ['country' => 'New Zealand', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NZ'],
            ['country' => 'Nicaragua', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NI'],
            ['country' => 'Niger', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NE'],
            ['country' => 'Nigeria', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NG'],
            ['country' => 'Niue', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NU'],
            ['country' => 'Norfolk Island', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NF'],
            ['country' => 'Northern Mariana Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MP'],
            ['country' => 'Norway', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'NO'],
            ['country' => 'Oman', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'OM'],
            ['country' => 'Pakistan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PK'],
            ['country' => 'Palau', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PW'],
            ['country' => 'Palestine, State of', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PS'],
            ['country' => 'Panama', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PA'],
            ['country' => 'Papua New Guinea', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PG'],
            ['country' => 'Paraguay', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PY'],
            ['country' => 'Peru', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PE'],
            ['country' => 'Philippines', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PH'],
            ['country' => 'Pitcairn', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PN'],
            ['country' => 'Poland', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PL'],
            ['country' => 'Portugal', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PT'],
            ['country' => 'Puerto Rico', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PR'],
            ['country' => 'Qatar', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'QA'],
            ['country' => 'Réunion', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'RE'],
            ['country' => 'Romania', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'RO'],
            ['country' => 'Russian Federation', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'RU'],
            ['country' => 'Rwanda', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'RW'],
            ['country' => 'Saint Barthélemy', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'BL'],
            ['country' => 'Saint Helena, Ascension and Tristan da Cunha', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SH'],
            ['country' => 'Saint Kitts and Nevis', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'KN'],
            ['country' => 'Saint Lucia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LC'],
            ['country' => 'Saint Martin (French part)', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'MF'],
            ['country' => 'Saint Pierre and Miquelon', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'PM'],
            ['country' => 'Saint Vincent and the Grenadines', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'VC'],
            ['country' => 'Samoa', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'WS'],
            ['country' => 'San Marino', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SM'],
            ['country' => 'Sao Tome and Principe', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'ST'],
            ['country' => 'Saudi Arabia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SA'],
            ['country' => 'Senegal', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SN'],
            ['country' => 'Serbia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'RS'],
            ['country' => 'Seychelles', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SC'],
            ['country' => 'Sierra Leone', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SL'],
            ['country' => 'Singapore', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SG'],
            ['country' => 'Sint Maarten (Dutch part)', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SX'],
            ['country' => 'Slovakia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SK'],
            ['country' => 'Slovenia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SI'],
            ['country' => 'Solomon Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SB'],
            ['country' => 'Somalia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SO'],
            ['country' => 'South Africa', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'ZA'],
            ['country' => 'South Georgia and the South Sandwich Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GS'],
            ['country' => 'South Sudan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SS'],
            ['country' => 'Spain', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'ES'],
            ['country' => 'Sri Lanka', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'LK'],
            ['country' => 'Sudan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SD'],
            ['country' => 'Suricountry', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SR'],
            ['country' => 'Svalbard and Jan Mayen', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SJ'],
            ['country' => 'Swaziland', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SZ'],
            ['country' => 'Sweden', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SE'],
            ['country' => 'Switzerland', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'CH'],
            ['country' => 'Syrian Arab Republic', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'SY'],
            ['country' => 'Taiwan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TW'],
            ['country' => 'Tajikistan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TJ'],
            ['country' => 'Tanzania, United Republic of', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TZ'],
            ['country' => 'Thailand', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TH'],
            ['country' => 'Timor-Leste', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TL'],
            ['country' => 'Togo', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TG'],
            ['country' => 'Tokelau', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TK'],
            ['country' => 'Tonga', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TO'],
            ['country' => 'Trinidad and Tobago', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TT'],
            ['country' => 'Tunisia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TN'],
            ['country' => 'Turkey', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TR'],
            ['country' => 'Turkmenistan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TM'],
            ['country' => 'Turks and Caicos Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TC'],
            ['country' => 'Tuvalu', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'TV'],
            ['country' => 'Uganda', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'UG'],
            ['country' => 'Ukraine', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'UA'],
            ['country' => 'United Arab Emirates', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'AE'],
            ['country' => 'United Kingdom', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'GB'],
            ['country' => 'United States', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'US'],
            ['country' => 'United States Minor Outlying Islands', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'UM'],
            ['country' => 'Uruguay', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'UY'],
            ['country' => 'Uzbekistan', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'UZ'],
            ['country' => 'Vanuatu', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'VU'],
            ['country' => 'Venezuela, Bolivarian Republic of', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'VE'],
            ['country' => 'Viet Nam', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'VN'],
            ['country' => 'Virgin Islands, British', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'VG'],
            ['country' => 'Virgin Islands, U.S.', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'VI'],
            ['country' => 'Wallis and Futuna', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'WF'],
            ['country' => 'Western Sahara', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'EH'],
            ['country' => 'Yemen', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'YE'],
            ['country' => 'Zambia', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'ZM'],
            ['country' => 'Zimbabwe', "created_at" => date("Y-m-d H:i:s"), 'currency' => 'ZW'],
        ];
        DB::table('countrys')->insert($countrys);
    }
}
